# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTTe2Sp-o1OP_PJyYLg1ACHbNlV_Gf6F

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

# Bloque 2: Creación de 'valor_total'
try:
    tiendas['valor_total'] = tiendas['Precio'] + tiendas['Costo de envío']
    print("✅ Columna 'valor_total' creada correctamente")
except KeyError as e:
    print(f"❌ Columna no encontrada al crear valor_total: {e}")
except Exception as e:
    print(f"❌ Error creando 'valor_total': {e}")

# Bloque 3: Análisis de facturación por tienda
try:
    facturacion_por_tienda = (
        tiendas
        .groupby('tienda_id')['valor_total']
        .sum()
        .reset_index(name='facturacion_total')
    )
    print("🔍 Facturación por tienda:")
    print(facturacion_por_tienda)
except Exception as e:
    print(f"❌ Error en análisis de facturación por tienda: {e}")

"""# 2. Ventas por categoría"""

# Bloque 4: Ventas por categoría por tienda
try:
    ventas_por_categoria = (
        tiendas
        .groupby(['tienda_id', 'Categoría del Producto'])
        .size()
        .reset_index(name='ventas')
        .sort_values(['tienda_id', 'ventas'], ascending=[True, False])
    )
    print("\n🔍 Ventas por categoría y tienda:")
    print(ventas_por_categoria)
except Exception as e:
    print(f"❌ Error en ventas por categoría por tienda: {e}")

"""# 3. Calificación promedio de la tienda

"""

# Bloque 5: Calificación promedio por tienda
try:
    calificacion_por_tienda = (
        tiendas
        .groupby('tienda_id')['Calificación']
        .mean()
        .reset_index(name='calificacion_promedio')
    )
    print("\n🔍 Calificación promedio por tienda:")
    print(calificacion_por_tienda)
except Exception as e:
    print(f"❌ Error en calificación promedio por tienda: {e}")



"""# 4. Productos más y menos vendidos"""

# Bloque 6: Productos más y menos vendidos por tienda
try:
    mas_menos = []
    for tid, df in tiendas.groupby('tienda_id'):
        ventas_prod = df.groupby('Producto').size()
        mas = ventas_prod.idxmax()
        menos = ventas_prod.idxmin()
        mas_menos.append({'tienda_id': tid,
                          'mas_vendido': mas,
                          'ventas_mas': int(ventas_prod.max()),
                          'menos_vendido': menos,
                          'ventas_menos': int(ventas_prod.min())})
    resumen_prod = pd.DataFrame(mas_menos)
    print("\n🔍 Productos más y menos vendidos por tienda:")
    print(resumen_prod)
except Exception as e:
    print(f"❌ Error en productos más/menos vendidos por tienda: {e}")



"""# 5. Envío promedio por tienda"""

# Bloque 7: Envío promedio por tienda
try:
    envio_promedio = (
        tiendas
        .groupby('tienda_id')['Costo de envío']
        .mean()
        .reset_index(name='envio_promedio')
    )
    print("\n🔍 Envío promedio por tienda:")
    print(envio_promedio)
except Exception as e:
    print(f"❌ Error en envío promedio por tienda: {e}")

# Relatorio para el Señor Juan
try:
    # Identificar tienda con menor facturación (lucro)
    tienda_menor = facturacion_por_tienda.loc[
        facturacion_por_tienda['facturacion_total'].idxmin(), 'tienda_id'
    ]
    valor_min = facturacion_por_tienda['facturacion_total'].min()

    reporte = f"""
Señor Juan,

Tras el análisis realizado:

1. La tienda con menor facturación total es {tienda_menor} con ${valor_min:,.2f}.
2. Se recomienda evaluar la venta o reestructuración de esta tienda para optimizar su rentabilidad.
"""
    print(reporte)
except Exception as e:
    print(f"❌ Error generando el relatorio: {e}")